version: '3.7'

networks:
  name: pgnetwork
  drivers: bridge
  scope:  local
  
services:
  postgres:
    image: postgres
    volumes:
      - postgresqldata:local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - pgnetwork
  
  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admi@example.com
      - PGADMIN_DEFAULT_PASSWORD=admi
    networks:
      - pgnetwork


  